version: '3.8'

services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - .env
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html
    restart: always
    depends_on:
      - wordpress

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    expose:
      - "3306"
    networks:
      - inception
    restart: always
    volumes:
      - db-volume:/var/lib/mysql

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/html
    restart: always

volumes:
  db-volume:
    driver: local
    driver_opts:
      device: /home/kichlee/data/db
      type: none
      o: bind
  wp-volume:
    driver: local
    driver_opts:
      device: /home/kichlee/data/web
      type: none
      o: bind

networks:
  inception:
    driver: bridge
